/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a full install. It is committed here so
// the initial scaffold type-checks before the first local dev run.
